-- Create roles if they don't exist
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'role_load') THEN
        CREATE ROLE role_load;
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'role_view') THEN
        CREATE ROLE role_view;
    END IF;
END $$;

-- Create intermediate views to match the Oracle production table names if needed
CREATE OR REPLACE VIEW DL_BIOMARKER_HOPANE_ AS SELECT * FROM DL_BIOMARKER_HOPANE;
CREATE OR REPLACE VIEW W_BOREHOLE_ AS SELECT borehole_id AS ID, ubhi AS UBHI, borehole_name AS BOREHOLE_NAME FROM W_BOREHOLE;

-- Drop the existing view first
DROP VIEW IF EXISTS DL_BIOMARKER_HOPANE_VW CASCADE;

-- Create the view exactly as provided
CREATE OR REPLACE VIEW DL_BIOMARKER_HOPANE_VW
AS
SELECT    
	BIOHP.ID,
	BH.UBHI,
	BIOHP.NAME,
	BIOHP.DEPTH_TOP,
	BIOHP.DEPTH_BOTTOM,
	BIOHP.OBJECT_NO,
	BIOHP.FORMATION,
	BIOHP.C27_TS,
	BIOHP.C27_TM,
	BIOHP.BCD,
	BIOHP.BNH,
	BIOHP.C29H,
	BIOHP.C29_TS,
	BIOHP.DIAHOPANE,
	BIOHP.C29_M,
	BIOHP.OLA,
	BIOHP.OLB,
	BIOHP.C30H,
	BIOHP.C30M,
	BIOHP.C31HH_S,
	BIOHP.C31HH_R,
	BIOHP.C32HH_S,
	BIOHP.C32HH_R,
	BIOHP.C33HH_S,
	BIOHP.C33HH_R,
	BIOHP.C34HH_S,
	BIOHP.C34HH_R,
	BIOHP.C35HH_S,
	BIOHP.C35HH_R,
	BIOHP.TOTAL_HH,
	BIOHP.TM_BY_TS,
	BIOHP.C27TS_BY_TS_PLUS_TM,
	BIOHP.C29H_BY_C30H,
	BIOHP.C30M_BY_C30H,
	BIOHP.C30H_BY_H_PLUS_M,
	BIOHP.C31H_S_BY_S_PLUS_R,
	BIOHP.C32H_S_BY_S_PLUS_R,
	BIOHP.C33H_S_BY_S_PLUS_R,
	BIOHP.C34H_S_BY_S_PLUS_R,
	BIOHP.C35H_S_BY_S_PLUS_R,
	BIOHP.HOMOHOPANE_INDEX,
	BIOHP.C35_S_BY_C34_S,
	BIOHP.BCD_INDEX,
	BIOHP.OLEANANE_INDEX,
	BIOHP.C29TS_BY_C29H_PLUS_C29TS,
	BIOHP.DIAHOPANE_INDEX,
	BIOHP.BNH_INDEX,
	BIOHP.C31HH_R_BY_C30H,
	BIOHP.C30_DIAHOPANE_BY_C29TS,
	BIOHP.PERC_C31HH,
	BIOHP.PERC_C32HH,
	BIOHP.PERC_C33HH,
	BIOHP.PERC_C34HH,
	BIOHP.PERC_C35HH,
	BIOHP.REMARKS,
	BIOHP.INSERT_USER,
	BIOHP.INSERT_DATE,
	BIOHP.UPDATE_USER,
	BIOHP.UPDATE_DATE,
	BIOHP.BOREHOLE_ID
FROM DL_BIOMARKER_HOPANE_ BIOHP, W_BOREHOLE_ BH
WHERE BH.ID = BIOHP.BOREHOLE_ID;

-- Apply grants
GRANT DELETE, INSERT, SELECT, UPDATE ON DL_BIOMARKER_HOPANE_VW TO ROLE_LOAD;
GRANT SELECT ON DL_BIOMARKER_HOPANE_VW TO ROLE_VIEW;
