-- GVMS - PostgreSQL Database Initialization Script

-- Create metabase database if it doesn't exist
SELECT 'CREATE DATABASE metabase_db'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'metabase_db')\gexec

-- Connect to ongc_lab (the primary database)
\c ongc_lab;

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Table 1: users
CREATE TABLE IF NOT EXISTS users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    hashed_password VARCHAR(255) NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL DEFAULT 'viewer', -- 'admin', 'researcher', 'viewer'
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table 2: petroleum_data
CREATE TABLE IF NOT EXISTS petroleum_data (
    id SERIAL PRIMARY KEY,
    sample_type VARCHAR(100) NOT NULL,
    well_name VARCHAR(100) NOT NULL,
    depth_from DOUBLE PRECISION NOT NULL,
    depth_interval DOUBLE PRECISION NOT NULL,
    toc DOUBLE PRECISION NOT NULL,
    s2 DOUBLE PRECISION NOT NULL,
    toc_classification VARCHAR(50) NOT NULL,
    s2_classification VARCHAR(50) NOT NULL,
    interpretation TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    uploaded_by UUID REFERENCES users(id) ON DELETE SET NULL
);

-- Table 3: upload_logs
CREATE TABLE IF NOT EXISTS upload_logs (
    id SERIAL PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    file_size INTEGER NOT NULL,
    total_rows INTEGER NOT NULL,
    imported_rows INTEGER NOT NULL,
    skipped_rows INTEGER NOT NULL,
    error_summary TEXT,
    uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    uploaded_by UUID REFERENCES users(id) ON DELETE SET NULL
);

-- Table 4: audit_logs
CREATE TABLE IF NOT EXISTS audit_logs (
    id SERIAL PRIMARY KEY,
    user_id UUID REFERENCES users(id) ON DELETE SET NULL,
    action VARCHAR(100) NOT NULL,
    resource VARCHAR(100) NOT NULL,
    details TEXT,
    ip_address VARCHAR(45),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_petroleum_well_name ON petroleum_data(well_name);
CREATE INDEX IF NOT EXISTS idx_petroleum_depth ON petroleum_data(depth_from);
CREATE INDEX IF NOT EXISTS idx_petroleum_toc ON petroleum_data(toc);
CREATE INDEX IF NOT EXISTS idx_petroleum_s2 ON petroleum_data(s2);
CREATE INDEX IF NOT EXISTS idx_petroleum_sample_type ON petroleum_data(sample_type);
CREATE INDEX IF NOT EXISTS idx_petroleum_well_depth ON petroleum_data(well_name, depth_from);

-- Audit Log index
CREATE INDEX IF NOT EXISTS idx_audit_user_action ON audit_logs(user_id, action);

-- ==================================================================================
-- Enterprise Dataset Registry & Versioning Tables
-- ==================================================================================

-- Table 5: dataset_registry
-- Stores configurable dataset definitions with dynamic column mappings and graph configs
CREATE TABLE IF NOT EXISTS dataset_registry (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    display_name VARCHAR(150) NOT NULL,
    sql_table_name VARCHAR(100),
    module VARCHAR(100) DEFAULT 'geochemistry',
    status VARCHAR(50) DEFAULT 'active',
    version VARCHAR(50) DEFAULT '1.0',
    description TEXT,
    mapping_config JSONB NOT NULL DEFAULT '{}',
    graph_config JSONB NOT NULL DEFAULT '[]',
    filter_config JSONB NOT NULL DEFAULT '[]',
    required_columns TEXT[] NOT NULL DEFAULT '{}',
    primary_depth_column VARCHAR(100),
    primary_well_column VARCHAR(100),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL
);

-- Table 6: dataset_versions
-- Tracks versioned file uploads per registered dataset
CREATE TABLE IF NOT EXISTS dataset_versions (
    id SERIAL PRIMARY KEY,
    dataset_id INTEGER NOT NULL REFERENCES dataset_registry(id) ON DELETE CASCADE,
    version_number INTEGER NOT NULL,
    filename VARCHAR(255) NOT NULL,
    file_size INTEGER NOT NULL DEFAULT 0,
    total_rows INTEGER NOT NULL DEFAULT 0,
    imported_rows INTEGER NOT NULL DEFAULT 0,
    skipped_rows INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(50) NOT NULL DEFAULT 'pending', -- 'pending', 'processing', 'completed', 'failed', 'rolled_back'
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    error_summary TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    uploaded_by UUID REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE(dataset_id, version_number)
);

-- Table 7: generic_dataset_records
-- High-throughput JSONB document store for arbitrary dataset rows
CREATE TABLE IF NOT EXISTS generic_dataset_records (
    id BIGSERIAL PRIMARY KEY,
    dataset_id INTEGER NOT NULL REFERENCES dataset_registry(id) ON DELETE CASCADE,
    version_id INTEGER NOT NULL REFERENCES dataset_versions(id) ON DELETE CASCADE,
    data JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Table 8: variable_registry
-- Stores variables definitions associated with datasets configuration
CREATE TABLE IF NOT EXISTS variable_registry (
    id SERIAL PRIMARY KEY,
    dataset_id INTEGER NOT NULL REFERENCES dataset_registry(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    display_name VARCHAR(150) NOT NULL,
    sql_column_name VARCHAR(100) NOT NULL,
    sql_data_type VARCHAR(50) NOT NULL,
    display_unit VARCHAR(50),
    is_numeric BOOLEAN NOT NULL DEFAULT TRUE,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    is_filterable BOOLEAN NOT NULL DEFAULT TRUE,
    chart_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    kpi_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    export_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    description TEXT,
    validation_rule TEXT,
    category VARCHAR(100),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(dataset_id, sql_column_name)
);

-- Table 9: version_record_mapping
-- Maps dynamic record IDs in target tables to versions for rollbacks
CREATE TABLE IF NOT EXISTS version_record_mapping (
    id SERIAL PRIMARY KEY,
    version_id INTEGER NOT NULL REFERENCES dataset_versions(id) ON DELETE CASCADE,
    record_id INTEGER NOT NULL
);

-- Table: W_BOREHOLE
-- Master borehole registry holding UBHI and Borehole Name details
CREATE TABLE IF NOT EXISTS W_BOREHOLE (
    BOREHOLE_ID SERIAL PRIMARY KEY,
    UBHI VARCHAR(64) UNIQUE,
    BOREHOLE_NAME VARCHAR(150) UNIQUE
);

-- Table 10: DL_CL_CORE_SOURCEROCK
-- Official table for Core Source Rock dataset
CREATE TABLE IF NOT EXISTS DL_CL_CORE_SOURCEROCK (
    ID SERIAL PRIMARY KEY,
    UBHI VARCHAR(64),
    BOREHOLE_NAME VARCHAR(255),
    CORE_SAMPLE_ID VARCHAR(64),
    CORE_TOP DOUBLE PRECISION,
    CORE_BASE DOUBLE PRECISION,
    ACTIVITY_TYPE VARCHAR(64),
    ANALYSIS_TYPE VARCHAR(64),
    TOP_DEPTH DOUBLE PRECISION,
    BOTTOM_DEPTH DOUBLE PRECISION,
    SEGMENT_POSITION VARCHAR(64),
    LITHOLOGY VARCHAR(64),
    LAYER_NAME VARCHAR(64),
    TOC VARCHAR(255),
    S1 VARCHAR(255),
    S2 VARCHAR(255),
    S2_EXTRACTION VARCHAR(255),
    S3 VARCHAR(255),
    TMAX VARCHAR(255),
    VRO VARCHAR(255),
    S2_S3 VARCHAR(255),
    PI VARCHAR(255),
    OSI VARCHAR(255),
    HI VARCHAR(255),
    OI VARCHAR(255),
    MINC VARCHAR(255),
    OTHERS VARCHAR(255),
    SPECIAL_OBS VARCHAR(255),
    DESCRIPTION VARCHAR(2000),
    YEAR VARCHAR(64),
    AUTHOR VARCHAR(64),
    ANALYSED_AT VARCHAR(64),
    REMARKS VARCHAR(2000),
    INSERT_USER VARCHAR(64),
    INSERT_DATE TIMESTAMP WITH TIME ZONE,
    UPDATE_USER VARCHAR(64),
    UPDATE_DATE TIMESTAMP WITH TIME ZONE,
    SEP_TEMP DOUBLE PRECISION,
    SEP_PRESS DOUBLE PRECISION,
    FTHP DOUBLE PRECISION,
    FTHT DOUBLE PRECISION,
    FRACTION_TYPE VARCHAR(64),
    DURATION DOUBLE PRECISION,
    SAMPLE_TOP DOUBLE PRECISION,
    SAMPLE_BOTTOM DOUBLE PRECISION,
    LAYER_TYPE VARCHAR(64),
    STRAT_SCOPE_ID DOUBLE PRECISION,
    TEST_NO VARCHAR(255),
    LAB_ANALYSIS_ONGC_ID INTEGER,
    BOREHOLE_ID INTEGER,
    CORE_ID INTEGER,
    CORE_SEGMENT_ID INTEGER
);

-- Performance Indexes for Registry Tables
CREATE INDEX IF NOT EXISTS idx_registry_name ON dataset_registry(name);
CREATE INDEX IF NOT EXISTS idx_versions_dataset ON dataset_versions(dataset_id);
CREATE INDEX IF NOT EXISTS idx_versions_active ON dataset_versions(dataset_id, is_active);
CREATE INDEX IF NOT EXISTS idx_records_dataset ON generic_dataset_records(dataset_id);
CREATE INDEX IF NOT EXISTS idx_records_version ON generic_dataset_records(version_id);
CREATE INDEX IF NOT EXISTS idx_records_data_gin ON generic_dataset_records USING GIN (data);

-- Table 10 (modified): DL_CL_CORE_SOURCEROCK
-- Keep core table definition as is.

-- Table 11: DL_CL_CUTTING_SOURCEROCK
CREATE TABLE IF NOT EXISTS DL_CL_CUTTING_SOURCEROCK (
    ID SERIAL PRIMARY KEY,
    UBHI VARCHAR(64),
    BOREHOLE_NAME VARCHAR(255),
    CUTTINGS_SAMPLE_ID VARCHAR(64),
    TOP_DEPTH DOUBLE PRECISION,
    BOTTOM_DEPTH DOUBLE PRECISION,
    ACTIVITY_TYPE VARCHAR(64),
    ANALYSIS_TYPE VARCHAR(64),
    SEGMENT_POSITION VARCHAR(64),
    LITHOLOGY VARCHAR(64),
    LAYER_NAME VARCHAR(64),
    TOC VARCHAR(255),
    S1 VARCHAR(255),
    S2 VARCHAR(255),
    S2_EXTRACTION VARCHAR(255),
    S3 VARCHAR(255),
    TMAX VARCHAR(255),
    VRO VARCHAR(255),
    S2_S3 VARCHAR(255),
    PI VARCHAR(255),
    OSI VARCHAR(255),
    HI VARCHAR(255),
    OI VARCHAR(255),
    MINC VARCHAR(255),
    OTHERS VARCHAR(255),
    SPECIAL_OBS VARCHAR(255),
    DESCRIPTION VARCHAR(2000),
    YEAR VARCHAR(64),
    AUTHOR VARCHAR(64),
    ANALYSED_AT VARCHAR(64),
    REMARKS VARCHAR(2000),
    INSERT_USER VARCHAR(64),
    INSERT_DATE TIMESTAMP WITH TIME ZONE,
    UPDATE_USER VARCHAR(64),
    UPDATE_DATE TIMESTAMP WITH TIME ZONE,
    SEP_TEMP DOUBLE PRECISION,
    SEP_PRESS DOUBLE PRECISION,
    FTHP DOUBLE PRECISION,
    FTHT DOUBLE PRECISION,
    FRACTION_TYPE VARCHAR(64),
    DURATION DOUBLE PRECISION,
    CUTTINGS_TOP DOUBLE PRECISION,
    CUTTINGS_BASE DOUBLE PRECISION,
    LAYER_TYPE VARCHAR(64),
    STRAT_SCOPE_ID DOUBLE PRECISION,
    TEST_NO VARCHAR(255),
    LAB_ANALYSIS_ONGC_ID INTEGER,
    BOREHOLE_ID INTEGER,
    CUTTINGS_ID INTEGER,
    PROPOSED_CODE VARCHAR(255),
    uploaded_by UUID
);

-- Table 12: DL_GAS_CHROMATOGRAPHY_
CREATE TABLE IF NOT EXISTS DL_GAS_CHROMATOGRAPHY_ (
    ID SERIAL PRIMARY KEY,
    UBHI VARCHAR(64),
    NAME VARCHAR(200),
    OBJECT_NUMBER VARCHAR(200),
    INTERVAL_TOP DOUBLE PRECISION,
    INTERVAL_BOTTOM DOUBLE PRECISION,
    FORMATION VARCHAR(500),
    MATERIAL_TYPE VARCHAR(200),
    ANALYSIS_DATE DATE,
    LOCATION VARCHAR(200),
    COLLECTION_DATE DATE,
    NC10 DOUBLE PRECISION,
    NC11 DOUBLE PRECISION,
    NC12 DOUBLE PRECISION,
    NC13 DOUBLE PRECISION,
    NC14 DOUBLE PRECISION,
    NC15 DOUBLE PRECISION,
    NC16 DOUBLE PRECISION,
    NC17 DOUBLE PRECISION,
    PR DOUBLE PRECISION,
    NC18 DOUBLE PRECISION,
    PH DOUBLE PRECISION,
    NC19 DOUBLE PRECISION,
    NC20 DOUBLE PRECISION,
    NC21 DOUBLE PRECISION,
    NC22 DOUBLE PRECISION,
    NC23 DOUBLE PRECISION,
    NC24 DOUBLE PRECISION,
    NC25 DOUBLE PRECISION,
    NC26 DOUBLE PRECISION,
    NC27 DOUBLE PRECISION,
    NC28 DOUBLE PRECISION,
    NC29 DOUBLE PRECISION,
    NC30 DOUBLE PRECISION,
    NC31 DOUBLE PRECISION,
    NC32 DOUBLE PRECISION,
    NC33 DOUBLE PRECISION,
    NC34 DOUBLE PRECISION,
    NC35 DOUBLE PRECISION,
    NC36 DOUBLE PRECISION,
    NC37 DOUBLE PRECISION,
    NC38 DOUBLE PRECISION,
    NC39 DOUBLE PRECISION,
    NC40 DOUBLE PRECISION,
    PR_BY_PH DOUBLE PRECISION,
    PR_BY_NC17 DOUBLE PRECISION,
    PH_BY_NC18 DOUBLE PRECISION,
    PR_NC17_BY_PH_NC18 DOUBLE PRECISION,
    NC21_NC22_BY_NC28_NC29 DOUBLE PRECISION,
    OEP_ODD_EVEN_PREF DOUBLE PRECISION,
    CP_INDEX DOUBLE PRECISION,
    TA_RATIO DOUBLE PRECISION,
    NC17_BY_NC29 DOUBLE PRECISION,
    PAQ DOUBLE PRECISION,
    NC17_BY_NC27 DOUBLE PRECISION,
    C_MAX DOUBLE PRECISION,
    ANALYSED_AT VARCHAR(200),
    REMARKS VARCHAR(2000),
    INSERT_USER VARCHAR(64),
    INSERT_DATE DATE,
    UPDATE_USER VARCHAR(64),
    UPDATE_DATE DATE,
    BOREHOLE_ID INTEGER,
    uploaded_by UUID
);

-- Table 13: DL_GCH_OIL_COMPOSITION_
CREATE TABLE IF NOT EXISTS DL_GCH_OIL_COMPOSITION_ (
    ID SERIAL PRIMARY KEY,
    UBHI VARCHAR(64),
    WELL_NAME VARCHAR(200),
    OBJECT_NUMBER VARCHAR(200),
    INTERVAL_TOP DOUBLE PRECISION,
    INTERVAL_BOTTOM DOUBLE PRECISION,
    FORMATION VARCHAR(500),
    MATERIAL_TYPE VARCHAR(500),
    ANALYSIS_DATE DATE,
    LOCATION VARCHAR(500),
    COLLECTION_DATE DATE,
    IBP DOUBLE PRECISION,
    WATER_CONTENT DOUBLE PRECISION,
    API_GRAVITY DOUBLE PRECISION,
    POUR_POINT DOUBLE PRECISION,
    SULFUR DOUBLE PRECISION,
    SAT_BY_ARO DOUBLE PRECISION,
    SAT DOUBLE PRECISION,
    AR DOUBLE PRECISION,
    ASP DOUBLE PRECISION,
    NSO DOUBLE PRECISION,
    ANALYSED_AT VARCHAR(200),
    REMARKS VARCHAR(2000),
    INSERT_USER VARCHAR(64),
    INSERT_DATE DATE,
    UPDATE_USER VARCHAR(64),
    UPDATE_DATE DATE,
    BOREHOLE_ID INTEGER,
    uploaded_by UUID
);

-- Table 14: DL_ISOTOPE_GAS_
CREATE TABLE IF NOT EXISTS DL_ISOTOPE_GAS_ (
    ID SERIAL PRIMARY KEY,
    UBHI VARCHAR(64),
    NAME VARCHAR(200),
    OBJECT_NUMBER VARCHAR(200),
    INTERVAL_TOP DOUBLE PRECISION,
    INTERVAL_BOTTOM DOUBLE PRECISION,
    FORMATION VARCHAR(500),
    MATERIAL_TYPE VARCHAR(200),
    COLLECTION_DATE DATE,
    C1 DOUBLE PRECISION,
    C2 DOUBLE PRECISION,
    C3 DOUBLE PRECISION,
    IC4 DOUBLE PRECISION,
    NC4 DOUBLE PRECISION,
    IC5 DOUBLE PRECISION,
    NC5 DOUBLE PRECISION,
    C6_PLUS DOUBLE PRECISION,
    C2_PLUS DOUBLE PRECISION,
    N2 DOUBLE PRECISION,
    CO2 DOUBLE PRECISION,
    HE DOUBLE PRECISION,
    HYDROGEN DOUBLE PRECISION,
    DELTA_C1 DOUBLE PRECISION,
    DELTA_C2 DOUBLE PRECISION,
    DELTA_C3 DOUBLE PRECISION,
    DELTA_IC4 DOUBLE PRECISION,
    DELTA_NC4 DOUBLE PRECISION,
    DELTA_IC5 DOUBLE PRECISION,
    DELTA_NC5 DOUBLE PRECISION,
    DELTA_CO2 DOUBLE PRECISION,
    C1_BY_C2_PLUS_C3 DOUBLE PRECISION,
    C2_BY_C3 DOUBLE PRECISION,
    DELTA_C2_BY_DELTA_C3 DOUBLE PRECISION,
    LN_C2_BY_C3 DOUBLE PRECISION,
    C1_BY_C2 DOUBLE PRECISION,
    LN_C1_BY_C2 DOUBLE PRECISION,
    ANALYSED_AT VARCHAR(200),
    REMARKS VARCHAR(2000),
    INSERT_USER VARCHAR(64),
    INSERT_DATE DATE,
    UPDATE_USER VARCHAR(64),
    UPDATE_DATE DATE,
    BOREHOLE_ID INTEGER,
    uploaded_by UUID
);

-- Table 15: DL_TRICYCLIC_TERPANE_
CREATE TABLE IF NOT EXISTS DL_TRICYCLIC_TERPANE_ (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(200),
    DEPTH DOUBLE PRECISION,
    C19 DOUBLE PRECISION,
    C20 DOUBLE PRECISION,
    C21 DOUBLE PRECISION,
    C22 DOUBLE PRECISION,
    C23 DOUBLE PRECISION,
    C24 DOUBLE PRECISION,
    C25R DOUBLE PRECISION,
    C25S DOUBLE PRECISION,
    C24TET DOUBLE PRECISION,
    C26R DOUBLE PRECISION,
    C26S DOUBLE PRECISION,
    TOTAL DOUBLE PRECISION,
    C19_RATIO DOUBLE PRECISION,
    C20_RATIO DOUBLE PRECISION,
    C21_RATIO DOUBLE PRECISION,
    C22_RATIO DOUBLE PRECISION,
    C23_RATIO DOUBLE PRECISION,
    C24_RATIO DOUBLE PRECISION,
    C25R_RATIO DOUBLE PRECISION,
    C25S_RATIO DOUBLE PRECISION,
    C24TET_RATIO DOUBLE PRECISION,
    C26R_RATIO DOUBLE PRECISION,
    C26S_RATIO DOUBLE PRECISION,
    REMARKS VARCHAR(2000),
    ANALYSED_AT VARCHAR(200),
    INSERT_USER VARCHAR(64),
    INSERT_DATE DATE,
    UPDATE_USER VARCHAR(64),
    UPDATE_DATE DATE,
    BOREHOLE_ID INTEGER,
    uploaded_by UUID
);

-- Table 16: DL_BIOMARKER_AROMATIC_
CREATE TABLE IF NOT EXISTS DL_BIOMARKER_AROMATIC_ (
    ID SERIAL PRIMARY KEY,
    UBHI VARCHAR(64),
    NAME VARCHAR(200),
    DEPTH DOUBLE PRECISION,
    OBJECT VARCHAR(200),
    FORMATION VARCHAR(500),
    DBT_DIBENZO DOUBLE PRECISION,
    PHE_PHENA DOUBLE PRECISION,
    DBT_BY_PHE DOUBLE PRECISION,
    MP_3 DOUBLE PRECISION,
    MP_2 DOUBLE PRECISION,
    MP_9 DOUBLE PRECISION,
    MP_1 DOUBLE PRECISION,
    MPI DOUBLE PRECISION,
    VRC DOUBLE PRECISION,
    NDR DOUBLE PRECISION,
    TMN_1_2_7 DOUBLE PRECISION,
    TMN_1_3_7 DOUBLE PRECISION,
    TMN_RATIO DOUBLE PRECISION,
    ETR DOUBLE PRECISION,
    ANALYSED_AT VARCHAR(2000),
    REMARKS VARCHAR(2000),
    INSERT_USER VARCHAR(64),
    INSERT_DATE DATE,
    UPDATE_USER VARCHAR(64),
    UPDATE_DATE DATE,
    BOREHOLE_ID INTEGER,
    uploaded_by UUID
);

-- Table 17: DL_BIOMARKER_HOPANE_
CREATE TABLE IF NOT EXISTS DL_BIOMARKER_HOPANE_ (
    ID SERIAL PRIMARY KEY,
    UBHI VARCHAR(64),
    NAME VARCHAR(200),
    DEPTH_TOP DOUBLE PRECISION,
    DEPTH_BOTTOM DOUBLE PRECISION,
    OBJECT_NO VARCHAR(200),
    FORMATION VARCHAR(500),
    C27_TS DOUBLE PRECISION,
    C27_TM DOUBLE PRECISION,
    BCD DOUBLE PRECISION,
    BNH DOUBLE PRECISION,
    C29H DOUBLE PRECISION,
    C29_TS DOUBLE PRECISION,
    DIAHOPANE DOUBLE PRECISION,
    C29_M DOUBLE PRECISION,
    OLA DOUBLE PRECISION,
    OLB DOUBLE PRECISION,
    C30H DOUBLE PRECISION,
    C30M DOUBLE PRECISION,
    C31HH_S DOUBLE PRECISION,
    C31HH_R DOUBLE PRECISION,
    C32HH_S DOUBLE PRECISION,
    C32HH_R DOUBLE PRECISION,
    C33HH_S DOUBLE PRECISION,
    C33HH_R DOUBLE PRECISION,
    C34HH_S DOUBLE PRECISION,
    C34HH_R DOUBLE PRECISION,
    C35HH_S DOUBLE PRECISION,
    C35HH_R DOUBLE PRECISION,
    TOTAL_HH DOUBLE PRECISION,
    TM_BY_TS DOUBLE PRECISION,
    C27TS_BY_TS_PLUS_TM DOUBLE PRECISION,
    C29H_BY_C30H DOUBLE PRECISION,
    C30M_BY_C30H DOUBLE PRECISION,
    C30H_BY_H_PLUS_M DOUBLE PRECISION,
    C31H_S_BY_S_PLUS_R DOUBLE PRECISION,
    C32H_S_BY_S_PLUS_R DOUBLE PRECISION,
    C33H_S_BY_S_PLUS_R DOUBLE PRECISION,
    C34H_S_BY_S_PLUS_R DOUBLE PRECISION,
    C35H_S_BY_S_PLUS_R DOUBLE PRECISION,
    HOMOHOPANE_INDEX DOUBLE PRECISION,
    C35_S_BY_C34_S DOUBLE PRECISION,
    BCD_INDEX DOUBLE PRECISION,
    OLEANANE_INDEX DOUBLE PRECISION,
    C29TS_BY_C29H_PLUS_C29TS DOUBLE PRECISION,
    DIAHOPANE_INDEX DOUBLE PRECISION,
    BNH_INDEX DOUBLE PRECISION,
    C31HH_R_BY_C30H DOUBLE PRECISION,
    C30_DIAHOPANE_BY_C29TS DOUBLE PRECISION,
    PERC_C31HH DOUBLE PRECISION,
    PERC_C32HH DOUBLE PRECISION,
    PERC_C33HH DOUBLE PRECISION,
    PERC_C34HH DOUBLE PRECISION,
    PERC_C35HH DOUBLE PRECISION,
    REMARKS VARCHAR(2000),
    INSERT_USER VARCHAR(64),
    INSERT_DATE DATE,
    UPDATE_USER VARCHAR(64),
    UPDATE_DATE DATE,
    BOREHOLE_ID INTEGER,
    uploaded_by UUID
);

-- Table 18: DL_BIOMARKER_PR_PH_
CREATE TABLE IF NOT EXISTS DL_BIOMARKER_PR_PH_ (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(200),
    DEPTH DOUBLE PRECISION,
    OBJECT VARCHAR(200),
    FORMATION VARCHAR(500),
    PRISTANE DOUBLE PRECISION,
    PHYTANE DOUBLE PRECISION,
    PR_BY_PH DOUBLE PRECISION,
    ANALYSED_AT VARCHAR(2000),
    REMARKS VARCHAR(2000),
    INSERT_USER VARCHAR(64),
    INSERT_DATE DATE,
    UPDATE_USER VARCHAR(64),
    UPDATE_DATE DATE,
    BOREHOLE_ID INTEGER,
    uploaded_by UUID
);

-- Table 19: DL_BIOMARKER_STERANE_
CREATE TABLE IF NOT EXISTS DL_BIOMARKER_STERANE_ (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(200),
    OBJECT_NO VARCHAR(200),
    DEPTH_TOP DOUBLE PRECISION,
    DEPTH_BOTTOM DOUBLE PRECISION,
    FORMATION VARCHAR(500),
    C27_DIASTERANE_BETA_ALPHA_S DOUBLE PRECISION,
    C27_DIASTERANE_BETA_ALPHA_R DOUBLE PRECISION,
    C27_STERANE_S DOUBLE PRECISION,
    C27_STERANE_BETA_BETA_R DOUBLE PRECISION,
    C27_STERANE_BETA_BETA_S DOUBLE PRECISION,
    C27_STERANE_R DOUBLE PRECISION,
    C28_DIASTERANE_BETA_ALPHA_S DOUBLE PRECISION,
    C28_DIASTERANE_BETA_ALPHA_R DOUBLE PRECISION,
    C28_STERANE_S DOUBLE PRECISION,
    C28_STERANE_BETA_BETA_R DOUBLE PRECISION,
    C28_STERANE_BETA_BETA_S DOUBLE PRECISION,
    C28_STERANE_R DOUBLE PRECISION,
    C29_DIASTERANE_BETA_ALPHA_S DOUBLE PRECISION,
    C29_DIASTERANE_BETA_ALPHA_R DOUBLE PRECISION,
    C29_STERANE_S DOUBLE PRECISION,
    C29_STERANE_BETA_BETA_R DOUBLE PRECISION,
    C29_STERANE_BETA_BETA_S DOUBLE PRECISION,
    C29_STERANE_R DOUBLE PRECISION,
    C27_DIASTERANE_INDEX DOUBLE PRECISION,
    C29_DIASTERANE_INDEX DOUBLE PRECISION,
    C28ST_BY_C29ST DOUBLE PRECISION,
    C27ST_PLUS_C28ST_PLUS_C29ST DOUBLE PRECISION,
    PERC_C27ST_R DOUBLE PRECISION,
    PERC_C28ST_R DOUBLE PRECISION,
    PERC_C29ST_R DOUBLE PRECISION,
    TOTAL_STERANE DOUBLE PRECISION,
    PERC_C27_ST DOUBLE PRECISION,
    PERC_C28_ST DOUBLE PRECISION,
    PERC_C29_ST DOUBLE PRECISION,
    C29_S_BY_S_PLUS_R DOUBLE PRECISION,
    C29_BB_BY_AA_PLUS_BB DOUBLE PRECISION,
    C27_DIAST_BY_C29_DIAST DOUBLE PRECISION,
    C27_ST_BY_C29_ST DOUBLE PRECISION,
    DIAS_C27_BY_C27_PLUS_C29 DOUBLE PRECISION,
    C28BBS_BY_C29BBS_STERANE DOUBLE PRECISION,
    C27R_BY_C27R_PLUS_C29R DOUBLE PRECISION,
    REMARKS VARCHAR(2000),
    ANALYSED_AT VARCHAR(2000),
    INSERT_USER VARCHAR(64),
    INSERT_DATE DATE,
    UPDATE_USER VARCHAR(64),
    UPDATE_DATE DATE,
    BOREHOLE_ID INTEGER,
    uploaded_by UUID
);

-- Performance Indexes
CREATE INDEX IF NOT EXISTS idx_registry_name ON dataset_registry(name);
CREATE INDEX IF NOT EXISTS idx_versions_dataset ON dataset_versions(dataset_id);
CREATE INDEX IF NOT EXISTS idx_versions_active ON dataset_versions(dataset_id, is_active);
CREATE INDEX IF NOT EXISTS idx_records_dataset ON generic_dataset_records(dataset_id);
CREATE INDEX IF NOT EXISTS idx_records_version ON generic_dataset_records(version_id);
CREATE INDEX IF NOT EXISTS idx_records_data_gin ON generic_dataset_records USING GIN (data);

-- Seed metadata configs (Datasets & Variables are seeded via Python scripts in practice,
-- but we include a basic SQL seed matching petroleum_geochem for backward compatibility and fallback)
INSERT INTO dataset_registry (name, display_name, sql_table_name, module, description, mapping_config, graph_config, filter_config, required_columns, primary_depth_column, primary_well_column)
VALUES (
    'petroleum_geochem',
    'Petroleum Geochemistry',
    'petroleum_data',
    'geochemistry',
    'Source rock evaluation dataset with TOC (wt%) and Pyrolysis S2 (mg/g) for kerogen potential assessment.',
    '{
        "sample_type": ["sample_type", "sample type", "sampletype", "type", "rock_type", "lithology"],
        "well_name": ["well_name", "well name", "well", "wellid", "well_id", "borehole"],
        "depth_from": ["depth_from", "depth from", "depth", "depth_m", "depth (m)", "md", "top_depth"],
        "depth_interval": ["depth_interval", "depth interval", "interval", "thickness", "step", "sample_interval"],
        "toc": ["toc", "toc%", "toc (wt%)", "toc_wt%", "total_organic_carbon"],
        "s2": ["s2", "s2 (mg/g)", "s2_mg_g", "pyrolysis_s2", "s2_peak"]
    }'::jsonb,
    '[
        {"type": "depth_profile", "x_axis": "toc", "y_axis": "depth_from", "title": "TOC Depth Profile", "color": "#003366"},
        {"type": "depth_profile", "x_axis": "s2", "y_axis": "depth_from", "title": "S2 Depth Profile", "color": "#D97706"},
        {"type": "scatter", "x_axis": "toc", "y_axis": "s2", "title": "TOC vs S2 Crossplot", "color_by": "toc_classification"},
        {"type": "histogram", "x_axis": "toc_classification", "title": "TOC Quality Distribution"},
        {"type": "histogram", "x_axis": "s2_classification", "title": "S2 Quality Distribution"}
    ]'::jsonb,
    '[
        {"name": "well_name", "type": "select", "label": "Well Name"},
        {"name": "sample_type", "type": "select", "label": "Lithology"}
    ]'::jsonb,
    ARRAY['well_name', 'depth_from', 'toc', 's2'],
    'depth_from',
    'well_name'
) ON CONFLICT (name) DO NOTHING;


